import Head from 'next/head';
import Header from './components/Header';
import Form from './components/Form';
import Footer from './components/Footer';
import Table from './components/Table';
import { useState } from 'react';
// import tableHeaders from 'data'

export default function Home() {

  const [places, setPlaces] = useState([])
  
  function newPlaceHandler(e) {
    e.preventDefault()
    const place = {
      name: e.target.placeName.value,
      minCust: e.target.minCust.value,
      maxCust: e.target.maxCust.value,
      avgCook: e.target.avgCook.value,
      id: places.length,
    };
    setPlaces([...places, place])
  }
  return (
    <>
      <Head>
        <title>Cookie Stand Admin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="">
        <Form newPlaceHandler={newPlaceHandler} />
        <Table places={places} />
      </main>
      <Footer places={places}/>
    </>
  )
}
